### ISSUE TITLE
Kaggle DR pretrained model

### ISSUE THREAD

**Issue by GuoleiSun** [xmengli999/CANet#3]
Hi, good work, did you try using Kaggle DR pretained model shared in your git and what's the result?
Also, for the DR pretrained model, what Kaggle images are used? 

Thanks a lot

**Comment by xmengli** [comment]
Using kaggle pretrained model will improve the result ~1%. In our paper, we use imagenet pretrained model.

**Comment by GuoleiSun** [comment]
Yes, thanks. What kaggle images do you use to train it?

**Comment by xmengli** [comment]
https://www.kaggle.com/c/diabetic-retinopathy-detection/data  This dataset

**Comment by xmengli** [comment]
https://www.kaggle.com/c/diabetic-retinopathy-detection/data This dataset

**Comment by GuoleiSun** [comment]
I see, thanks a lot

**Comment by GuoleiSun** [comment]
Hi, another question: how do u train Kaggle DR pertained model? do u use **ImageNet** pretrained model as initialisation when training on Kaggle images?

**Comment by ahmedgamaleldin14** [comment]
@GuoleiSun Doing lots of experiments, I think it is always better to use ImageNet as a pretrained model.
